package:
  name: juu-object-detection-protos
  version: 0.1

source:
  path: ./

requirements:
  build:
    - python

  run:
    - python
    - grpcio

outputs:
  - name: juu-object-detection-protos
    files:
      - api

about:
  home: https://github.com/kunadawa/object-detection-protos
  summary: holds the protobuf files for the protobuf messages that are exchanged between the various services
  license: MIT
