package:
  name: juu_object_detection_protos
  version: 0.1

source:
  path: ./

requirements:
  build:
    - python

  run:
    - python
    - grpcio

about:
  home: https://github.com/kunadawa/object-detection-protos
  summary: holds the protobuf files for the protobuf messages that are exchanged between object detection services
  license: MIT
  #readme: ./README.md
